# -*- mode: ruby -*-
# vi: set ft=ruby

Vagrant.configure("2") do |config|
config.ssh.insert_key = false
config.vm.provider :virtualbox do |vb|
vb.customize ["modifyvm", :id, "--memory", "2064"]
end

config.vm.define "mysql" do |mysql|
mysql.vm.hostname = "kubernetes-main.dev"
mysql.vm.box = "bento/ubuntu-22.04"
mysql.vm.network "private_network", ip: "192.168.56.10"
end

end
