# -*- mode: ruby -*-
# vi: set ft=ruby

Vagrant.configure("2") do |config|
config.ssh.insert_key = false
config.vm.provider :virtualbox do |vb|
vb.customize ["modifyvm", :id, "--memory", "2064"]
end

config.vm.define "monitor" do |monitor|
monitor.vm.hostname = "monitor.dev"
monitor.vm.box = "bento/ubuntu-22.04"
monitor.vm.network "forwarded_port", guest: 9090, host: 9090
monitor.vm.network "private_network", ip: "192.168.56.10"
end

config.vm.define "host1" do |host1|
host1.vm.hostname = "host1.dev"
host1.vm.box = "bento/ubuntu-22.04"
host1.vm.network "private_network", ip: "192.168.56.20"
end

config.vm.define "host2" do |host2|
host2.vm.hostname = "host2.dev"
host2.vm.box = "bento/ubuntu-22.04"
host2.vm.network "private_network", ip: "192.168.56.30"
end

end
