---
- name: Setup Wireguard server
  hosts: "servers"
  become: true
  roles:
    - { role: roles/wireguard_server }

# - name: Setup Wireguard client
#   hosts: "clients"
#   become: true
#   roles:
#     - { role: roles/wireguard_client }
