- name: Download Prometheus node exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ prometheus_node_exporter_version }}/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp/prometheus-node-exporter-{{ prometheus_node_exporter_version }}.tar.gz
  tags: [ "install" ]

- name: Extract Prometheus node exporter
  ansible.builtin.unarchive:
    src: /tmp/prometheus-node-exporter-{{ prometheus_node_exporter_version }}.tar.gz
    dest: /tmp
    remote_src: yes
  tags: [ "install" ]

- name: Move execs to binary
  ansible.builtin.copy:
    src: /tmp/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64/node_exporter
    dest: /usr/local/bin
    remote_src: yes
    owner: root
    group: root
    mode: "0775"
  tags: [ "install" ]

- name: Create Prometheus node exporter group
  ansible.builtin.group:
    name: node_exporter
    state: present
  tags: [ "install" ]

- name: Create Prometheus node exporter user
  ansible.builtin.user:
    name: node_exporter
    group: node_exporter
    state: present
  tags: [ "install" ]

- name: Create configuration dir
  ansible.builtin.file:
    path: /etc/node_exporter
    state: directory
    owner: node_exporter
    group: node_exporter
    mode: "0775"
  tags: [ "install" ]

- name: Remove tmp files and dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64
    - /tmp/prometheus-node-exporter-{{ prometheus_node_exporter_version }}.tar.gz
  tags: [ "install" ]

- name: Copy Prometheus node exporter SystemD service
  ansible.builtin.copy:
    src: templates/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: "0644"
  tags: [ "config" ]

- name: Enable the Prometheus node exporter service
  ansible.builtin.systemd:
    name: node_exporter.service
    state: started
    enabled: true
    daemon_reload: true
  tags: [ "config" ]
