# -*- mode: ruby -*-
# vi: set ft=ruby

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2064"]
    end

    config.vm.define "web1" do |web1|
        web1.vm.hostname = "web1.dev"
        web1.vm.box = "bento/ubuntu-22.04"
        web1.vm.network "private_network", ip: "192.168.56.10"
    end

    config.vm.define "web2" do |web2|
        web2.vm.hostname = "web2.dev"
        web2.vm.box = "bento/ubuntu-22.04"
        web2.vm.network "private_network", ip: "192.168.56.11"
    end

    config.vm.define "proxy" do |proxy|
        proxy.vm.hostname = "proxy.dev"
        proxy.vm.box = "bento/ubuntu-22.04"
        proxy.vm.network "forwarded_port", guest: 80, host: 8080
        proxy.vm.network "private_network", ip: "192.168.56.20"
    end

    config.vm.define "db" do |db|
        db.vm.hostname = "db.dev"
        db.vm.box = "bento/ubuntu-22.04"
        db.vm.network "private_network", ip: "192.168.56.30"
    end
end
